# Site setings
name: 'Mustafa Salman'
description: 'GRA at TReNDS Center & PhD student in ECE at Georgia Tech'
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Hi, this is Mustafa Salman. I am a graduate research assistant at the TReNDS Center, Atlanta, GA, and a PhD student in ECE at Georgia Tech."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://esalman.github.io
disqus: 
mailchimp_url: 
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: esalman@gatech.edu
contact_page_description: 
thankyou_page_description: "Your message has been successfully sent. I will contact you very soon!"

# Social links
twitter: 'esalman'
facebook: 
github: 'esalman'
codepen: 
dribbble: 
medium: 
instagram: 
pinterest: 
linkedin: 'mustafa-salman-a0267216'
producthunt: 
quora: 

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: CV
    url: http://esalman.com/MSS-CV-latest.pdf
  # - text: Style Guide
  #   url: /style-guide
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
