# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Mustafa Salman
tagline:          
description:      GRA at TReNDS Center & PhD student in ECE at Georgia Tech
# url:              https://esalman.com/
url:              https://127.0.0.1:4000/
baseurl:          
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           Mustafa Salman
  url:            https://twitter.com/esalman

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
